[project]
name = "adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.11.0",
    "google>=3.0.0",
    "mcp-web-extractor-riversoft>=0.1.2",
    "google-adk>=0.2.0",
    "dotenv>=0.9.9",
]
